version: "3.8"

services:
  # Serviço do banco de dados
  db:
    image: postgres:14
    container_name: taskout_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: taskout_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - taskout-network

  # Serviço da API Node.js
  api:
    build: .
    container_name: taskout_api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - taskout-network
    # Caso queira desenvolvimento com auto-reload, adicione volume do código:
    # volumes:
    #   - ./:/app

# Definição de volumes para persistência do banco
volumes:
  dbdata:

# Definição da rede
networks:
  taskout-network:
    driver: bridge
